services:
  web:
    build:
      context: ./bugtracker
      dockerfile: Dockerfile.prod
    command: gunicorn bugtracker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8001:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:

