# Generated by Django 4.2.2 on 2023-07-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='public',
            field=models.BooleanField(choices=[(True, 'Public'), (False, 'Private')], default=False),
        ),
    ]
