# Generated by Django 4.2.2 on 2023-07-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
