# Generated by Django 4.2.2 on 2023-07-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_ticket_edited_on_alter_ticket_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='edited_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
