# Generated by Django 4.2.2 on 2023-07-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_ticket_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solved',
            field=models.BooleanField(choices=[(True, 'Solved'), (False, 'Not solved')], default=False),
        ),
    ]
