# Generated by Django 4.2.2 on 2023-09-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_ticket_solved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='slug',
        ),
        migrations.AddField(
            model_name='project',
            name='permalink',
            field=models.CharField(default='a', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='permalink',
            field=models.CharField(default='b', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
