# Generated by Django 4.2.2 on 2023-09-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_remove_project_slug_remove_ticket_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-edited_on', '-solved']},
        ),
    ]
